1.0.0
itk-dev-rpa/digital-post-ukendt-adresse pull request #2
Opened 2024-10-04 12:14 UTC by bakspace-itk

2024-10-07 10:51 UTC, ghbm-itk submitted a review, later dismissed

2024-10-07 10:51 UTC, ghbm-itk commented on robot_framework/process.py
> +def encrypt_data(cpr, first_name) -> str:
Missing hints

2024-10-07 11:42 UTC, bakspace-itk commented on robot_framework/process.py
> +    query = "SELECT * FROM [DWH].[Mart].[AdresseAktuel] WHERE Vejkode = 9901 AND Myndighed = 751"
Because it is more readable.

2024-10-09 09:00 UTC, bakspace-itk reviewed
Changes implemented

2024-10-09 09:12 UTC, ghbm-itk requested changes

2024-10-09 09:12 UTC, ghbm-itk commented on robot_framework/process.py
> +    query = "SELECT * FROM [DWH].[Mart].[AdresseAktuel] WHERE Vejkode = 9901 AND Myndighed = 751"
!

2024-10-16 09:11 UTC, ghbm-itk approved these changes

2024-10-16 11:31 UTC, merged